### ISSUE TITLE
File versioning

### ISSUE THREAD

**Issue by readio** [diglin/Diglin_UIOptimization#12]
Hey there. 

I have implemented this module and its a great improvement on file sizes, thanks.

I'm having an issue with the versioning of files though. It renames my files with 'filename' + '_1_cp.css'.

No matter how many times I update the file and flush the cache I cannot get it to update the '1_cp' part. 
This is causing issues as I'm using browser caching and cannot force the css to update. Any ides on how to fix this?

Cheers
Darren

**Comment by diglin** [comment]
the PR #20 solves it for yuicompressor use case
